[package]
name = "rust-web"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.35"
itertools = "0.12.1"
r2d2_mysql = "24.0.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[dev-dependencies]
rstest = "0.18.2"
